#!/bin/bash

#此脚本针对虚拟机的ip配置以及yum配置
#只针对下面网段ip的配置
#192.168.2.0
#192.168.4.0
#201.1.1.0
#201.1.2.0

read -p "请输入你的网卡名称:"  card
read -p "请输入你要配的ip地址:" ip
read -p "是否添加主机名(y/n)" bool


ip_part1=`echo $ip | awk -F. '{print $1}'`
ip_part2=`echo $ip | awk -F. '{print $2}'`
ip_part3=`echo $ip | awk -F. '{print $3}'`
ip_part4=`echo $ip | awk -F. '{print $4}'`

#定义yum源
gateway=`echo $ip | sed -r 's/(.*)\.(.*)\.(.*)\.(.*)/\1.\2.\3.254/'`
yum_resource="ftp://$gateway/rhel7"


add_ip (){

if [ `nmcli connection show | grep -q $card` ];then

        #echo "有$card网卡"
        nmcli connection modify $card ipv4.method manual ipv4.addresses $ip/24 connection.autoconnect yes  &> /dev/null
else
        #echo "没有$card网卡"
        nmcli connection add type ethernet con-name $card ifname $card autoconnect yes
        nmcli connection modify $card ipv4.method manual ipv4.addresses $ip/24 connection.autoconnect yes  &> /dev/null
fi

nmcli connection up $card

}


add_yum (){

num=$(yum repolist |awk '/repolist/{print $2}' |sed 's/,//')

if [ $num  -le 0 ];then
rm -rf /etc/yum.repos.d/*.repo
echo "
[rhel7]
name=rhel7
enabled=1
gpgcheck=0
baseurl='$yum_resource'
"  > /etc/yum.repos.d/rhel.repo
fi

}

add_hostname (){
if [ $bool == "y" ];then
   read -p "请输入你的主机名:" name 
   hostnamectl set-hostname $name
   echo 1 | passwd --stdin root
else
   exit 4
fi



}



if [ $ip_part1 -eq 192 ] &&  [ $ip_part2 -eq 201 ];then

        echo "只能输入192网段和201网段!!!"
	exit 3

elif [ $ip_part1 -eq 192 ];then

        if [ $ip_part3 -eq 2 ] &&  [ $ip_part3 -eq 4 ];then
               echo "只能输入192.168.2.0网段和192.168.4.0网段！！！"
	       exit 6
        else
               add_ip
               add_yum
	       add_hostname
        fi

else

        if [ $ip_part3 -eq 1 ] &&  [ $ip_part3 -eq 2 ];then
               echo "只能输入201.1.1.0网段和201.1.2.0网段"
	       exit 5
        else
               add_ip
               add_yum
	       add_hostname
        fi
fi

