#!/bin/bash
IPS=`awk -F= '{print $2}' data`
PASSWORD=1
 
ssh_copy_id (){
	rpm -q expect || yum -y install expect
	[ -e /root/.ssh/id_rsa ] || ssh-keygen   -f /root/.ssh/id_rsa    -N ''

         expect -c "set timeout -1;
         spawn ssh-copy-id $1;                                
         expect {
                 *(yes/no)*  {send -- yes\r;exp_continue;}
                 *password:* {send -- $2\r;exp_continue;}  
                 eof         {exit 0;}
         }";
 
}
for ip in $IPS
do
ssh_copy_id $ip $PASSWORD
done

